"""Removed director

Revision ID: 626ad4e79195
Revises: cd0cec22e308
Create Date: 2024-02-07 14:50:31.604248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626ad4e79195'
down_revision = 'cd0cec22e308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.drop_column('director')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
